Feat/#30
2023-Winter-Bootcamp-Team-I/frontend pull request #37
Opened 2024-01-14 14:19 UTC by yyg47

## 🛠️ 변경사항
get books
put books
연동 완료

put 은 UI 가 완성되지 않았으므로 테스트까지는 완료 되었으나 아직 UI 와 연동은 하지 않았습니다
</br>
</br>

## ☝️ 유의사항
- 
</br>
</br>

## ❗체크리스트
- [ ] 하나의 메소드는 최소의 기능만 하도록 설정했나요?
- [ ] 수정 가능하도록 유연하게 작성했나요?
- [ ] 필요 없는 import문 등을 삭제했나요?
- [ ] 기존의 코드에 영향이 없는 것을 확인하였나요?

2024-01-14 15:25 UTC, youlimsongs requested changes
주석으로 설명 부탁드려요!

2024-01-14 15:48 UTC, yyg47 commented
주석 추가했습니다

2024-01-14 16:57 UTC, youlimsongs reviewed
getBooks(1)은 임의로 해놓으신 건가요?

2024-01-15 16:28 UTC, youlimsongs approved these changes
수고하셨습니다!

2024-01-15 16:29 UTC, merged